# Generated by Django 5.1.7 on 2025-04-04 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0003_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='mesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante.mesa'),
        ),
    ]
